version: '3'

services:
  MySql:
    image: mysql:${MYSQL_VERSION}
    container_name: infonete-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306
    volumes:
      - "${MYSQL_DATA}:/var/lib/mysql"
      - "${MYSQL_INIT_FILES}:/docker-entrypoint-initdb.d"
      - "${MYSQL_CONF}:/etc/mysql/conf.d/custom.cnf"

  PHP:
    image: php:${PHP_VERSION}
    container_name: infonete-app
    expose:
      - 80
      - 443
    ports:
      - "${PHP_PORT}:80"
      - "${PHP_SECURE_PORT}:443"
    volumes:
      - ./app/:/var/www/html
    links:
      - MySql
    command: sh ./docker-scripts/docker-php.sh
